FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backendap/response_app.py app.py
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8300"]

