FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backendap/capture_app.py app.py
COPY db ./db
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8100"]